name: CI/CD Workflow for driver-did-factom

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Build and Push
      uses: danubetech/github-action-docker-build-push@master
      env:
        MAVEN_SETTINGS: ${{secrets.MAVEN_SETTINGS}}
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_FILE: docker/Dockerfile
        CONTAINER_TAG: sphereon/driver-did-factom:latest
